# Generated by Django 2.0.8 on 2018-11-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20181117_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='result',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
