# Generated by Django 2.0.8 on 2019-01-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20190113_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.Task'),
            preserve_default=False,
        ),
    ]
