# Generated by Django 2.0.10 on 2019-01-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20190116_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='max_num',
            new_name='max_tagged_num',
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_tasks',
            field=models.ManyToManyField(to='login.Task'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='users',
            field=models.ManyToManyField(related_name='sub_tasks_tagged', to='login.User'),
        ),
        migrations.AlterField(
            model_name='task',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
