# Generated by Django 2.0.10 on 2019-01-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20190120_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='num_tagged',
            field=models.IntegerField(default=0),
        ),
    ]
