# Generated by Django 2.0.10 on 2019-01-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20190120_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_time',
            field=models.DateTimeField(default='2018-11-24 19:55:03.641391'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(default='2018-11-24 19:55:03.641391'),
        ),
    ]
