# Generated by Django 2.0.10 on 2019-01-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20190121_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='credit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='total_credits',
            field=models.IntegerField(default=1000),
        ),
    ]
