# Generated by Django 2.0.10 on 2019-01-25 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20190122_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_tasks', to='login.User'),
        ),
    ]
