# Generated by Django 2.0.10 on 2019-01-25 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20190125_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='released_tasks', to='login.User'),
        ),
    ]
