# Generated by Django 2.0.10 on 2019-01-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20190130_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='users',
            field=models.ManyToManyField(related_name='sub_tasks_tagged', through='login.Label', to='login.User'),
        ),
    ]
