# Generated by Django 2.0.10 on 2019-02-13 21:23

from django.db import migrations, models
import django.utils.timezone
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_auto_20190213_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='image',
        ),
        migrations.AddField(
            model_name='subtask',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, max_length=256, upload_to=login.models.file_directory_path),
            preserve_default=False,
        ),
    ]
