# Generated by Django 2.1 on 2019-02-17 04:11

from django.db import migrations, models
import django.db.models.deletion
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_auto_20190213_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=256, upload_to=login.models.screenshot_directory_path)),
                ('sub_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.SubTask')),
            ],
        ),
    ]
