# Generated by Django 2.1 on 2019-02-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_user_num_label_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_level',
            field=models.IntegerField(default=1),
        ),
    ]
