# Generated by Django 2.1 on 2019-02-28 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_auto_20190226_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuser',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskuser',
            name='is_grabbed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskuser',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskuser',
            name='num_label_reviewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskuser',
            name='num_label_unreviewed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='taskuser',
            name='pre_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_task_users', to='login.User'),
        ),
        migrations.AlterField(
            model_name='label',
            name='sub_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.SubTask'),
        ),
        migrations.AlterField(
            model_name='label',
            name='task_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.TaskUser'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_tasks', to='login.User'),
        ),
        migrations.AlterField(
            model_name='taskuser',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.Task'),
        ),
    ]
