# Generated by Django 2.1 on 2019-02-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_auto_20190228_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='redo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskuser',
            name='redo',
            field=models.BooleanField(default=False),
        ),
    ]
