# Generated by Django 2.1.7 on 2019-04-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_auto_20190228_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks_to_examine',
            field=models.ManyToManyField(related_name='to_examine', to='login.Task'),
        ),
    ]
