# Generated by Django 2.2 on 2019-04-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_user_tasks_to_examine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskuser',
            old_name='is_grabbed',
            new_name='has_grabbed',
        ),
        migrations.RemoveField(
            model_name='label',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='label',
            name='is_unreviewed',
        ),
        migrations.RemoveField(
            model_name='label',
            name='redo',
        ),
        migrations.RemoveField(
            model_name='taskuser',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='taskuser',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='taskuser',
            name='num_label_reviewed',
        ),
        migrations.RemoveField(
            model_name='taskuser',
            name='pre_user',
        ),
        migrations.RemoveField(
            model_name='taskuser',
            name='redo',
        ),
        migrations.AddField(
            model_name='label',
            name='status',
            field=models.CharField(default='untagged', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='num_worker',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskuser',
            name='num_label_rejected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taskuser',
            name='status',
            field=models.CharField(default='doing', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskuser',
            name='num_label_unreviewed',
            field=models.IntegerField(default=-1),
        ),
    ]
