# Generated by Django 2.1.7 on 2019-05-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_auto_20190417_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='callers',
            field=models.TextField(default=''),
        ),
    ]
