# Generated by Django 2.0.8 on 2018-11-17 12:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20181117_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['c_time']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['c_time']},
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='content',
        ),
        migrations.AddField(
            model_name='subtask',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, max_length=256, upload_to=login.models.file_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_created', to='login.User'),
        ),
        migrations.AlterField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(related_name='tasks_owned', to='login.User'),
        ),
    ]
