# Generated by Django 2.1 on 2019-02-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_auto_20190217_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Label'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='image',
            field=models.FileField(max_length=256, upload_to=''),
        ),
    ]
