# Generated by Django 2.1 on 2019-02-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_screenshot_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_label_accepted',
            field=models.IntegerField(default=1),
        ),
    ]
