# Generated by Django 2.0.8 on 2019-01-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20181124_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='is_tagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='c_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
