# Generated by Django 2.0.10 on 2019-02-13 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_subtask_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='kind',
            field=models.IntegerField(default=1),
        ),
    ]
