# Generated by Django 2.0.10 on 2019-02-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_task_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='kind',
            new_name='type',
        ),
    ]
